name: Publish TrailerFlix on gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install dependencies
        run: yarn
      - name: deploy
        run: |
          git config --global user.email "k.vivekk07@gmail.com"
          git config --global user.name "Vivekk07"
          yarn run deploy
